### ISSUE TITLE
《99 行代码光线追踪解析》一文的typo与疑问

### ISSUE THREAD

**Issue by SnailSword** [xieguanglei/xieguanglei.github.io#1]
首先非常感谢你如此高质量的博文，读了之后收获很大。

里面有应该是几个公式和描述的笔误，感觉博客提PR不太合适，我整理了一下写在这里[https://github.com/SnailSword/xieguanglei.github.io/commit/d046190d46bbda0174cc9d46e6055b3a456f9615](https://github.com/SnailSword/xieguanglei.github.io/commit/d046190d46bbda0174cc9d46e6055b3a456f9615)了，你有空可以看下需不需要调整一下。

然后还有几个问题想请教下：
1. 在折射情况中，深度大于2次用RR判断要取折射还是取反射时，为什么要用把0-1的RE映射成0.25-0.75的P，不直接用RE呢？
2. 折射光比例`𝑅𝜃=𝑅0+(1−𝑅0)(1−cos𝜃1)^5`中，文章中我理解`𝜃1`代表的是入射光线，但是代码里，`c = 1-(into?-ddn:tdir.dot(n))` 好像往光线向球内时c是入射光线，向球外射的时候是出射光线
3. 每种材质返回的结果，为什么是自己的颜色乘入射的颜色呢，如`f.mult(radiance(Ray(x,d),depth,Xi))` 因为BRDF返回结果和自己的颜色成正比？就算是成正比，为啥就可以直接用物体自身颜色代替了？
4. 漫反射情况中，设定`u` `v` `w`三个正交向量时，取`u` 用了`u=((fabs(w.x)>.1?Vec(0,1):Vec(1))%w).norm()`，这里为什么要判断`fabs(w.x)`？

**Comment by xieguanglei** [comment]
嗨，隔得有些久，我需要再看一遍，然后才可能讨论这些问题哈。稍晚两天哈。

对了，typo 那个，非常感谢！

**Comment by xieguanglei** [comment]
1. 神奇数的使用还是挺常见的。这里的作用是吧 Re 从 [0,1] 映射到 [0.25, 0.75]，保证了即使反射光的比例很小(如0.05)，也能够强行提升到 0.25，保证至少有 0.25 的可能性随机到反射光或折射光。为了渲染结果的显著性，违背物理规律，使用神奇数这些手段应该挺常见的。在这个例子中，我**猜测**如果直接用 Re 的话，折射效果就不太看得出来（也许 1.在符合该参数真实世界场景中就是看不出，2. 或者因为一些其他的系统级的 bias 如人眼的自动HDR / 屏幕颜色曲线误差，按照真实物理规律渲染后就看不出）。

2. `𝑅𝜃=𝑅0+(1−𝑅0)(1−cos𝜃1)^5` 这个是根据折射率的公式推算出来的，R0 是通过两侧介质的折射率 n1/n2 推算出来的，𝜃1 表示 **n1 这一侧**的「入射角」，光路可逆，所以光线从球外入射和球内出射时，𝜃1 的含义是不同的。

3. 反射光颜色和入射光颜色成正比，也和反射表面的颜色成正比，就是这样呀（比如红光照白色物体，或白光照红色物体，反射都是红光），应该没什么问题吧？另外，也没有「直接用物体自身颜色代替」啊，`f.mult` 这里的 `mult` 就是相乘的意思呀。

4. `fabs(w.x)` 这个似乎也没什么特别的吧？如果不写 `fabs(w.x)>.1` 就要写 `w.x>.1 || w.x<-.1` 了呗。

PS：typo 的话你想提 PR 就提 PR 呗，我觉得没啥不合适的。可以往 source 分支（有 md 源文件）提哈，合并到 source 后会触发 CI 自动部署的（哈哈）。不提也 OK，发下一篇文章的时候再一起改吧（懒）。

**Comment by SnailSword** [comment]
感谢解惑！太感动了！

对于问题3，我是理解了结果是应该和表面颜色成正比，但这里并没有乘一个比例系数，所以这里渲染出来的和实际其实颜色不一样的？我又参考了 [https://www.bilibili.com/video/BV1X7411F744?p=17](https://www.bilibili.com/video/BV1X7411F744?p=17)这个视频12:10开始解释的部分，这个比例系数貌似应该是`1/pi`，所以这里真实的颜色应该是`f.mult(radiance(Ray(x,d),depth,Xi))*(1/pi)` ，不知道我理解的对不对。

对于问题4，上面我没有表述清楚疑问点，现在也基本理解了，他是把`fabs(w.x)<.1`的都近似看在x轴上的点了。

再次感谢，我这就提一下PR。

**Comment by xieguanglei** [comment]
@SnailSword 常数项系数不用太在意

**Comment by SnailSword** [comment]
好的谢谢
